version: "3.7"

services:

  flask_webapp:
    build: ./flask
    env_file: 
      - flask.env
    container_name: flask_webapp
    restart: always
    volumes:
      - flask-resources:/app/homepage/static/resources
      - reqlog:/tmp/reqlog
      - errlog:/tmp/errlog
    expose:
      - 8080
    depends_on:
      - db

  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx_web_server:
    build: ./nginx
    container_name: nginx_web_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-errors:/var/log/nginx
      - /etc/ssl:/etc/ssl # dhparams file
      - /etc/letsencrypt/live:/etc/letsencrypt/live # current certificate
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive # all certificates (symlinks from /live points here)

volumes:
  postgres-data:
    driver: local
  reqlog:
    driver: local
  errlog:
    driver: local
  nginx-errors:
      driver: local
  flask-resources:
    driver: local
